name: Proposal
description: Propose a non-trivial change to Project-Guidance.
title: "Title: "
labels: "Proposal"
body:
  - type: markdown
    attributes:
      value: |
        Have you read the [Contributing Guidelines](https://github.com/Kushal997-das/Project-Guidance/blob/main/CONTRIBUTING.md) ?

  - type: textarea #description
    attributes:
      label: Is your proposal related to a problem? Please describe.
      description: A clear and concise description of what the proposal is.
    validations:
      required: true

  - type: textarea #Additional Context
    attributes:
      label: Add any other context or screenshots about the proposal request here.
      description: Any miscellaneous context you'd like to give.
