# Generated by Django 3.2.4 on 2021-06-24 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('toDoList', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topic',
            new_name='Category',
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='todolist',
            options={'ordering': ['-created']},
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='topic',
            new_name='category',
        ),
        migrations.RenameField(
            model_name='todolist',
            old_name='text_field',
            new_name='content',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='date_due',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='header',
        ),
        migrations.RemoveField(
            model_name='todolist',
            name='made',
        ),
        migrations.AddField(
            model_name='todolist',
            name='created',
            field=models.DateField(default='2021-06-24'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='due_date',
            field=models.DateField(default='2021-06-24'),
        ),
        migrations.AddField(
            model_name='todolist',
            name='title',
            field=models.CharField(default='general', max_length=250),
        ),
    ]
