# Generated by Django 3.2.4 on 2021-06-23 13:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Topic',
                'verbose_name_plural': 'Topics',
            },
        ),
        migrations.CreateModel(
            name='ToDoList',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('header', models.CharField(max_length=100)),
                ('text_field', models.TextField(blank=True)),
                ('made', models.DateField(default='23-06-2021')),
                ('date_due', models.DateField(default='23-06-2021')),
                ('topic', models.ForeignKey(default='general', on_delete=django.db.models.deletion.CASCADE, to='toDoList.topic')),
            ],
            options={
                'ordering': ['-made'],
            },
        ),
    ]
